/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AbilityScoreBlock: typeof import('./src/components/CharacterCreator/shared/AbilityScoreBlock.vue')['default']
    AbilityScoreGrid: typeof import('./src/components/CharacterCreator/shared/AbilityScoreGrid.vue')['default']
    AbilityScoreHeader: typeof import('./src/components/CharacterCreator/shared/AbilityScoreHeader.vue')['default']
    AbilityScores: typeof import('./src/components/CharacterCreator/steps/AbilityScores.vue')['default']
    AccessControlDialog: typeof import('./src/components/AccessControlDialog.vue')['default']
    AdminAuthDialog: typeof import('./src/components/AdminAuthDialog.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    BackgroundSelector: typeof import('./src/components/CharacterCreator/shared/BackgroundSelector.vue')['default']
    BackstoryPersonality: typeof import('./src/components/CharacterCreator/shared/BackstoryPersonality.vue')['default']
    BasicDetails: typeof import('./src/components/CharacterCreator/shared/BasicDetails.vue')['default']
    CharacterCreatorMain: typeof import('./src/components/CharacterCreator/CharacterCreatorMain.vue')['default']
    CharacterCreatorStepper: typeof import('./src/components/CharacterCreator/CharacterCreatorStepper.vue')['default']
    CharacterHeader: typeof import('./src/components/CharacterCreator/shared/CharacterHeader.vue')['default']
    CharacterInformation: typeof import('./src/components/CharacterCreator/steps/CharacterInformation.vue')['default']
    CharacterSummary: typeof import('./src/components/CharacterCreator/steps/CharacterSummary.vue')['default']
    ClassAbilityTips: typeof import('./src/components/CharacterCreator/shared/ClassAbilityTips.vue')['default']
    ClassSelector: typeof import('./src/components/CharacterCreator/shared/ClassSelector.vue')['default']
    EquipmentAndGear: typeof import('./src/components/CharacterCreator/steps/EquipmentAndGear.vue')['default']
    EquipmentLanguages: typeof import('./src/components/CharacterCreator/shared/EquipmentLanguages.vue')['default']
    FeatsList: typeof import('./src/components/CharacterCreator/shared/FeatsList.vue')['default']
    FeaturesAndTraits: typeof import('./src/components/CharacterCreator/steps/FeaturesAndTraits.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpeciesSelector: typeof import('./src/components/CharacterCreator/shared/SpeciesSelector.vue')['default']
    SpeciesTraits: typeof import('./src/components/CharacterCreator/shared/SpeciesTraits.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    WeaponsCantripsList: typeof import('./src/components/CharacterCreator/shared/WeaponsCantripsList.vue')['default']
  }
}
